version: '3.8'

services:
  fastapi_app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - AWS_REGION=<AWS_REGION>
      - SQS_QUEUE_URL=<SQS_QUEUE_URL>
      - AWS_ACCESS_KEY_ID=<AWS_ACCESS_KEY_ID>
      - AWS_SECRET_ACCESS_KEY=<AWS_SECRET_ACCESS_KEY>
      - AWS_SESSION_TOKEN=<AWS_SESSION_TOKEN>
