name: pipeline

on:
  push:
    branches:
      - main

env:
  REGION_DEFAULT: "us-east-1"
  CLUSTER_NAME: "tech-challenge"



jobs:

  # unit-test:
  #   runs-on: ubuntu-latest
    
  #   steps:
  #     # Checkout do código
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     # Configuração do Python
  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.11' # Escolha a versão do Python desejada

  #     # Instalação de dependências
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt

  #     # Execução dos testes com pytest
  #     - name: Run unit tests
  #       run: |
  #         pytest --cov=src
        
  push_to_registry:
      runs-on: ubuntu-latest
      # needs: unit-test
      steps:
        -
          name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        -
          name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
          name: Build and push
          uses: docker/build-push-action@v6
          with:
            # context: 
            push: true
            tags: mauriciohm/sqs-api:latest
   
  deploy-Prod:
    name: Deploy AWS Academy
    runs-on: ubuntu-latest
    needs: push_to_registry
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ID }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - name: Download task definition
        run: |
          aws ecs update-service --cluster fiap --service sqs-pub2 --force-new-deployment
